layers:
  Graphite:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - '='
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - \
  - '`'
  - B
  - L
  - D
  - W
  - Z
  - {t: '''', s: _}
  - F
  - O
  - U
  - J
  - ;
  - {t: '&caps_word', h: CAPS}
  - N
  - R
  - T
  - S
  - G
  - Y
  - H
  - A
  - E
  - I
  - {t: ',', s: '?'}
  - F13
  - Q
  - X
  - M
  - C
  - V
  - {t: ESC, h: Function}
  - LCTRL
  - DEL
  - LGUI
  - LALT
  - RET
  - K
  - P
  - .
  - '-'
  - {t: /, s: <}
  - F14
  - {t: '&rgb_ug_status_macro', h: Magic}
  - HOME
  - END
  - LEFT
  - RIGHT
  - {t: BSPC, h: Cursor}
  - LSHFT
  - LGUI
  - TAB
  - SPACE
  - Symbol
  - UP
  - DOWN
  - PG UP
  - PG DN
  - {t: '&rgb_ug_status_macro', h: Magic}
  QWERTY:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - '='
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - \
  - '`'
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - /
  - {t: '&caps_word', h: CAPS}
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ;
  - ''''
  - F13
  - Z
  - X
  - C
  - V
  - B
  - {t: ESC, h: Function}
  - LCTRL
  - DEL
  - LGUI
  - LALT
  - RET
  - N
  - M
  - ','
  - .
  - /
  - F14
  - {t: '&rgb_ug_status_macro', h: Magic}
  - HOME
  - END
  - LEFT
  - RIGHT
  - {t: BSPC, h: Cursor}
  - LSHFT
  - LGUI
  - TAB
  - SPACE
  - Symbol
  - UP
  - DOWN
  - PG UP
  - PG DN
  - {t: '&rgb_ug_status_macro', h: Magic}
  ColemakDH:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - '='
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - \
  - '`'
  - Q
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - ''''
  - '-'
  - {t: '&caps_word', h: CAPS}
  - A
  - R
  - S
  - T
  - G
  - M
  - N
  - E
  - I
  - O
  - ;
  - F13
  - Z
  - X
  - C
  - D
  - V
  - {t: ESC, h: Function}
  - LCTRL
  - DEL
  - LGUI
  - LALT
  - RET
  - K
  - H
  - ','
  - .
  - /
  - F14
  - {t: '&rgb_ug_status_macro', h: Magic}
  - HOME
  - END
  - LEFT
  - RIGHT
  - {t: BSPC, h: Cursor}
  - LSHFT
  - LGUI
  - TAB
  - SPACE
  - Symbol
  - UP
  - DOWN
  - PG UP
  - PG DN
  - {t: '&rgb_ug_status_macro', h: Magic}
  MTGAP:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - '='
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - \
  - '`'
  - Y
  - P
  - O
  - U
  - J
  - K
  - D
  - L
  - C
  - W
  - X
  - {t: '&caps_word', h: CAPS}
  - I
  - N
  - E
  - A
  - {t: ',', s: ':'}
  - M
  - H
  - T
  - S
  - R
  - Q
  - F13
  - /
  - '?'
  - ''''
  - {t: ., s: ;}
  - _
  - {t: ESC, h: Function}
  - LCTRL
  - DEL
  - LGUI
  - LALT
  - RET
  - B
  - F
  - G
  - V
  - Z
  - F14
  - {t: '&rgb_ug_status_macro', h: Magic}
  - HOME
  - END
  - LEFT
  - RIGHT
  - {t: BSPC, h: Cursor}
  - LSHFT
  - LGUI
  - TAB
  - SPACE
  - Symbol
  - UP
  - DOWN
  - PG UP
  - PG DN
  - {t: '&rgb_ug_status_macro', h: Magic}
  Magic:
  - BT CLR
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - BT CLR ALL
  - {t: Gaming, h: toggle}
  - {t: QWERTY, h: toggle}
  - {t: ColemakDH, h: toggle}
  - {t: MTGAP, h: toggle}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - RGB SPI
  - RGB SAI
  - RGB HUI
  - RGB BRI
  - RGB TOG
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bootloader'
  - RGB SPD
  - RGB SAD
  - RGB HUD
  - RGB BRD
  - RGB EFF
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bootloader'
  - '&sys_reset'
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bt_2'
  - '&bt_3'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&sys_reset'
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - '&bt_0'
  - '&bt_1'
  - OUT USB
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  Cursor:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - LG(K)
  - LC(LEFT)
  - LG(LS(LBKT))
  - {t: LSHFT, h: sticky}
  - LG(LS(RBKT))
  - LC(RIGHT)
  - PG UP
  - HOME
  - UP
  - END
  - DEL
  - ''
  - LG(F)
  - LGUI
  - LALT
  - LCTRL
  - LSHFT
  - LG(S)
  - PG DN
  - LEFT
  - DOWN
  - RIGHT
  - RET
  - ''
  - LG(I)
  - LG(Z)
  - LG(X)
  - LG(C)
  - LG(V)
  - LG(A)
  - ''
  - ''
  - ''
  - LS(LA(LEFT))
  - LA(BSPC)
  - LA(DEL)
  - ''
  - BSPC
  - ''
  - ''
  - ''
  - ''
  - LG(Q)
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - LS(LA(RIGHT))
  - LA(LEFT)
  - LA(RIGHT)
  - ''
  - ''
  - ''
  - ''
  - ''
  Number:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ^
  - '#'
  - $
  - '~'
  - '!'
  - '|'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '%'
  - '7'
  - '8'
  - '9'
  - ':'
  - K
  - KP NUM
  - LGUI
  - LALT
  - LCTRL
  - LSHFT
  - ''
  - +
  - '4'
  - '5'
  - '6'
  - '-'
  - J
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - <
  - '>'
  - '='
  - '*'
  - '1'
  - '2'
  - '3'
  - /
  - LS(G)
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ','
  - .
  - '0'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '@'
  Function:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - MEDIA HOME
  - PLAY
  - PREV
  - NEXT
  - STOP
  - EJECT
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - WWW
  - F7
  - F8
  - F9
  - F10
  - F13
  - ''
  - LGUI
  - LALT
  - LCTRL
  - LSHFT
  - ''
  - CALC
  - F4
  - F5
  - F6
  - F11
  - F14
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - PREV
  - NEXT
  - PP
  - AL FILES
  - F1
  - F2
  - F3
  - F12
  - F15
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - MUTE
  - VOL DN
  - VOL UP
  - BRI MAX
  - BRI UP
  - BRI DN
  - BRI MIN
  - BRI AUTO
  Symbol:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '`'
  - (
  - )
  - ;
  - ','
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '!'
  - '{'
  - ''''
  - '"'
  - '}'
  - '?'
  - {t: ▽, type: trans}
  - LSHFT
  - LCTRL
  - LALT
  - LGUI
  - ''
  - '#'
  - ^
  - '='
  - _
  - $
  - '*'
  - {t: ▽, type: trans}
  - BSPC
  - TAB
  - SPACE
  - RET
  - ''
  - '~'
  - <
  - '|'
  - '-'
  - '>'
  - /
  - \
  - .
  - '*'
  - ''
  - ''
  - ''
  - {t: ▽, type: trans}
  - DEL
  - LS(TAB)
  - ''
  - ''
  - ''
  - '@'
  - '&'
  - '['
  - ']'
  - +
  - '%'
  - ':'
  - ;
  - ''
  - ''
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  Gaming:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '-'
  - '`'
  - B
  - N
  - M
  - ''''
  - B
  - N
  - M
  - ','
  - .
  - /
  - T
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - G
  - LSHFT
  - A
  - S
  - D
  - F
  - ESC
  - RET
  - PAUSE BREAK
  - BSPC
  - DEL
  - RET
  - G
  - H
  - J
  - K
  - L
  - ;
  - V
  - LCTRL
  - Z
  - X
  - C
  - SPACE
  - LALT
  - LGUI
  - {t: Gaming, h: toggle}
  - TAB
  - E
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
